version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run lint"
          command: "echo linting..."

workflows:
  lint-workflow:
    jobs:
      - lint
