name: Continuous Deployment Process

on: workflow_dispatch

jobs:
  develop:
    runs-on: ubuntu-latest
    environment:
      # Preview Staging
      name: develop
      url: 'https://github.com/antenordev/pipeline-boilerplate'
    steps:

    - name: Run Deploy Staging
      run: echo Deploy Homologation
  
  staging:
    needs: develop
    runs-on: ubuntu-latest
    steps:

    - name: Run Pre-Production
      run: echo Staging Area
  
  main:
    needs: staging
    runs-on: ubuntu-latest
    environment:
      name: main
      # Preview Production
      url: 'https://github.com/antenordev/pipeline-boilerplate'
    steps:
    
    - name: Run Deploy Production
      run: echo Deploy Production