name: Continuous Delivery Process
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - main
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: echo Linting

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run Build
        run: echo Building
        
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Test
        run: echo Testing
  
  develop:
    runs-on: ubuntu-latest
    environment:
      # Preview Staging
      name: develop
      url: 'https://github.com/antenordev/pipeline-boilerplate'
    needs: test
    steps:
      - name: Run Deploy Staging
        run: echo Deploy Homologation
  
  staging:
    runs-on: ubuntu-latest
    needs: develop
    steps:
      - name: Run Pre-Production
        run: echo Staging Area
  
  main:
    runs-on: ubuntu-latest
    environment:
      name: main
      # Preview Production
      url: 'https://github.com/antenordev/pipeline-boilerplate'
    needs: staging
    steps:
      - name: Run Deploy Production
        run: echo Deploy Production
