name: CI Process
on:
  workflow_dispatch:
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Linting

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run a one-line script
        run: echo Building
  
  develop:
    runs-on: ubuntu-latest
    environment:
      name: develop
      # Preview Develop
      url: 'https://github.com/antenordev/pipeline-boilerplate'
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Develop
  
  staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      # Preview Staging
      url: 'https://github.com/antenordev/pipeline-boilerplate'
    needs: develop
    steps:
      - name: Run a one-line script
        run: echo Staging
  
  main:
    runs-on: ubuntu-latest
    environment:
      name: main
      # Preview Main
      url: 'https://github.com/antenordev/pipeline-boilerplate'
    needs: staging
    steps:
      - name: Run a one-line script
        run: echo Main
