name: Continuous Integration Process
on: [push, pull_request]
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run lint
        run: echo linting
      - name: Check commit message
        uses: wagoid/commitlint-github-action@v1

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run build
        run: echo building
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run test
        run: echo testing
