name: Continuous Integration Process
on: [push, pull_request]
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: echo Linting

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run Build
        run: echo Building
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Test
        run: echo Testing
