name: CI Process
on: [push, pull_request]
  
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Linting

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run a one-line script
        run: echo Building
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Test
