name: Continuous Integration Process

on: [pull_request]
  
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Run lint
      run: echo linting...
    - name: Checkout latest version
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Check commit message
      uses: wagoid/commitlint-github-action@v1
    
    - name: Check With nodejs ^12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Lint With yarn
      run: yarn lint
      
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Run build...
      run: echo building
      
    - name: With yarn for Install Dependencies
      run: yarn
    - name: Build With yarn
      run: yarn build
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run test...
      run: echo testing
    
    - name: Test With yarn
      run: yarn test
